version: '2'

services:
  drinkman:
    image: ghcr.io/agdsn/drinkman:master
    command: uwsgi --ini uwsgi.ini
    ports:
      - "8000:8000"
    environment:
      DJANGO_SECRET: SECRET
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: drinkman
      DB_USER: postgres
      DB_PW: password
    restart: always
