# Generated by Django 2.2.7 on 2019-11-28 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinkman', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.TextField(),
        ),
    ]
