# Generated by Django 2.2.7 on 2019-12-18 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinkman', '0003_auto_20191204_1754'),
        ('drinkman', '0003_auto_20191203_2058'),
    ]

    operations = [
    ]
