# Generated by Django 3.0.2 on 2020-01-08 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinkman', '0006_auto_20200106_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='purchases',
            field=models.IntegerField(default=0),
        ),
    ]
