# Generated by Django 3.0.2 on 2020-02-25 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinkman', '0007_item_purchases'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hide_log',
            field=models.BooleanField(default=0),
        ),
    ]
