# Generated by Django 4.0.3 on 2022-08-29 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinkman', '0009_auto_20220301_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('balance', models.IntegerField(default=0)),
                ('reduce_step', models.IntegerField(default=10)),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount',
            field=models.IntegerField(null=True),
        ),
    ]
