# Generated by Django 4.0.3 on 2022-08-30 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drinkman', '0010_discount_transaction_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='drinkman.location'),
        ),
    ]
