name: Drinkman Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build the Docker image
        run: docker build -f Dockerfile -t ghcr.io/agdsn/drinkman:${GITHUB_REF_NAME} .

      - name: Push to Github registry
        run: docker push ghcr.io/agdsn/drinkman:${GITHUB_REF_NAME}
